let members=[];
const $=id=>document.getElementById(id);
const POINTS=[[12,8,8],[37,7,10],[62,6,13],[87,5,16],[112,4,20],[137,3,25],[162,2,30],[187,2,35],[212,1,40],[237,1,45],[99999,0,50]];
document.addEventListener("DOMContentLoaded",()=>{$("confirm").onclick=confirmText;$("calc").onclick=calculate;loadRatingData();});
async function loadRatingData(){try{const r=await fetch("../data/rating_data_all.csv",{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const t=await r.text();const rows=parseCSV(t);const dates=rows.map(x=>new Date(String(x["日付"]||"").replaceAll("/","-"))).filter(x=>!isNaN(x));if(dates.length)$("lastUpdated").textContent="最終更新日："+dates.sort((a,b)=>a-b).at(-1).toISOString().slice(0,10)}catch(e){$("lastUpdated").textContent="最終更新日：取得できません";}}
function parseCandidateNumber(s){s=String(s).replace(/\D/g,"");if(s.length>=8)return Number(s.slice(-7));if(s.length===7||(s.length===6&&s.startsWith("9")))return Number(s);return null}
function parseText(text){const lines=text.normalize("NFKC").split(/\r?\n/).map(x=>x.trim()).filter(Boolean),out=[],used=new Set();for(let i=0;i<lines.length;i++){if(/^\d{6,}$/.test(lines[i])){const id=parseCandidateNumber(lines[i]);const name=lines[i+1]||"不明";const rt=/^\d+$/.test(lines[i+2]||"")?Number(lines[i+2]):((lines[i+2]||"")==="初"?"初":null);if(id&&!used.has(id)){out.push({id,name,rating:rt??0});used.add(id)}i+=2}}return out}
function confirmText(){members=parseText($("inputText").value);$("membersCard").classList.remove("hidden");$("calcCard").classList.remove("hidden");$("status").className="status ok";$("status").textContent=`${members.length}名を抽出しました。`;$("members").innerHTML=members.length?table(members.map((m,i)=>({番号:i+1,会員番号:m.id,氏名:m.name,レイティング:m.rating})),["番号","会員番号","氏名","レイティング"]):"<p>参加者を抽出できませんでした。</p>";$("target").innerHTML=members.map((m,i)=>`<option value="${i}">${i+1}. ${esc(m.name)} (${m.id})</option>`).join("");$("target").onchange=renderOpponents;renderOpponents()}
function renderOpponents(){const t=Number($("target").value||0);$("opponents").innerHTML=members.filter((_,i)=>i!==t).map((m,i)=>`<label><input type="checkbox" class="opp" value="${members.indexOf(m)}"> ${esc(m.name)} (${m.id}) / ${m.rating}</label>`).join("<br>")}
function calculate(){const t=Number($("target").value);const base=Number(members[t].rating);const checked=[...document.querySelectorAll(".opp:checked")].map(x=>Number(x.value));let total=0;const rows=[];for(const i of checked){const r=Number(members[i].rating);const diff=Math.abs(base-r);const rec=POINTS.find(x=>diff<=x[0])||POINTS.at(-1);rows.push({相手:members[i].name,相手レイティング:r,差:diff,勝ち:"+"+rec[1],負け:"-"+rec[2]});total+=rec[1]}$("calcResult").innerHTML=`<p>基準選手：${esc(members[t].name)} / 現在 ${base}</p>${table(rows,["相手","相手レイティング","差","勝ち","負け"])}<p><strong>勝った場合の増加合計：+${total}</strong></p>`}
function table(rows,cols){return "<div class='table-wrap'><table><thead><tr>"+cols.map(c=>`<th>${esc(c)}</th>`).join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+cols.map(c=>`<td>${esc(r[c]??"")}</td>`).join("")+"</tr>").join("")+"</tbody></table></div>"}
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===","&&!q){row.push(cell);cell="";continue}if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;row.push(cell);cell="";if(row.some(x=>x.trim()))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??"").trim()])))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}